#!/usr/bin/env bash
# Read-only system discovery for the HEART OF GOLD telemetry panel.
# Writes nothing itself; redirect its stdout to docs/DISCOVERY.md.
set -u
r() { printf '\n### `%s`\n\n```text\n' "$*"; bash -c "$*" 2>&1 | sed 's/^/  /' || true; printf '```\n'; }
say() { printf '\n## %s\n' "$*"; }

printf '# DISCOVERY — %s\n\nGenerated by tools/discover.sh at %s\nMode: READ-ONLY (no sudo, no writes)\n' \
  "$(hostname -f 2>/dev/null || hostname)" "$(date -Is)"

say "1. Host / OS / kernel"
r uname -a; r cat /etc/os-release; r uptime; r timedatectl show -p Timezone,NTPSynchronized --value
r hostnamectl status; r getconf LONG_BIT

say "2. Motherboard / firmware (some DMI fields are root-only on Ubuntu)"
r cat /sys/class/dmi/id/sys_vendor /sys/class/dmi/id/product_name /sys/class/dmi/id/board_name
r cat /sys/class/dmi/id/bios_vendor /sys/class/dmi/id/bios_version /sys/class/dmi/id/bios_date

say "3. CPU — cores vs threads, model string, frequency control"
r 'lscpu'
r 'grep -m1 "model name" /proc/cpuinfo'
r 'echo "logical=$(nproc)"; lscpu -p=CPU,CORE 2>/dev/null | grep -v "^#" | sort -u -t, -k2,2 | wc -l | sed "s/^/physical_cores=~/"'
r 'ls /sys/devices/system/cpu/cpufreq/ 2>&1; cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor /sys/devices/system/cpu/cpufreq/policy0/scaling_cur_freq 2>&1'
r 'cat /proc/loadavg'

say "4. Memory"
r free -h
r 'grep -E "^(MemTotal|MemAvailable|Buffers|Cached|SwapTotal|SwapFree|SReclaimable):" /proc/meminfo'
r 'stat -fc %T /sys/fs/cgroup 2>/dev/null'

say "5. DISPLAY ADAPTERS — CRITICAL: which device owns the motherboard HDMI"
r 'lspci -nnk | grep -iE -A3 "vga|3d|display controller"'
r 'for d in /sys/class/drm/card*/; do echo "== $d driver=$(basename "$(readlink -f "$d/device/driver" 2>/dev/null)" 2>/dev/null)"; done'
r 'for c in /sys/class/drm/card*-*/; do n=$(basename "$c"); s=$(cat "$c/status" 2>/dev/null); e=$(cat "$c/enabled" 2>/dev/null); drv=$(basename "$(readlink -f "$c/device/driver" 2>/dev/null)" 2>/dev/null); printf "%-28s status=%-12s enabled=%-10s driver=%s\n" "$n" "${s:-?}" "${e:-?}" "${drv:-?}"; done'
r 'for c in /sys/class/drm/card*-*/; do n=$(basename "$c"); m=$(cat "$c/modes" 2>/dev/null | head -4 | tr "\n" " "); [ -n "$m" ] && printf "%-24s modes: %s\n" "$n" "$m"; done'
say "   iGPU presence check (does the CPU graphics device exist at all?)"
r 'ls -l /sys/bus/pci/drivers/ 2>/dev/null | grep -iE "amdgpu|vga|i915|nouveau" || echo "no matching driver symlink found"'

say "6. NVIDIA — telemetry source for GPU0 / GPU1 panels (read-only)"
r 'command -v nvidia-smi && nvidia-smi --query-gpu=index,name,uuid,driver_version,memory.total,memory.used,temperature.gpu,utilization.gpu,power.draw,clocks.sm --format=csv,noheader'
r 'cat /proc/driver/nvidia/version 2>&1 | head -3'
r 'ls -l /dev/nvidia* 2>&1 | head -12'
r 'ls -l /dev/dri/ 2>&1'
r 'cat /sys/module/nvidia_drm/parameters/modeset 2>&1'

say "7. Graphics session / compositor (decides kiosk + rotation strategy)"
r 'echo "XDG_SESSION_TYPE=${XDG_SESSION_TYPE:-unset} DISPLAY=${DISPLAY:-unset} WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-unset}"'
r 'command -v loginctl >/dev/null && loginctl list-sessions --no-legend 2>&1 | head -5'
r 'pgrep -a -x "Xorg Xwayland gnome-shell gdm-x-session sddm wayland mutter kwin_x11 kwin_wayland" 2>/dev/null | head -10 || echo "no display server process visible to this user"'
r 'command -v xrandr >/dev/null && echo "xrandr present" || echo "xrandr absent"'
r 'command -v chromium >/dev/null || command -v chromium-browser >/dev/null || command -v google-chrome >/dev/null || echo "no chromium-family browser found (needed for kiosk mode)"'

say "8. Thermal sensors — hwmon enumeration (Marvin THERMALS box)"
r 'for h in /sys/class/hwmon/hwmon*/; do printf "%s name=%s label=%s\n" "$(basename "$h")" "$(cat "$h/hwmon_name" 2>/dev/null || echo ?)" "$(cat "$h/device/label" 2>/dev/null || cat "$h/label" 2>/dev/null || echo ?)"; done'
r 'for h in /sys/class/hwmon/hwmon*/; do echo "== $(basename "$h") $(cat "$h/hwmon_name" 2>/dev/null)"; for t in "$h"temp*_input; do [ -e "$t" ] || continue; b=${t%_input}; printf "   %-16s = %6s   label=%s max=%s crit=%s\n" "$(basename "$t")" "$(cat "$t")" "$(cat "${b}_label" 2>/dev/null || echo -)" "$(cat "${b}_max" 2>/dev/null || echo -)" "$(cat "${b}_crit" 2>/dev/null || echo -)"; done; done'

say "9. FAN RPM — the probe most likely to come back empty (decides FAN BANK 1/2)"
r 'found=0; for f in /sys/class/hwmon/hwmon*/fan*_input; do [ -e "$f" ] || continue; found=1; b=${f%_input}; printf "   %-46s = %6s label=%s target=%s\n" "$f" "$(cat "$f")" "$(cat "${b}_label" 2>/dev/null || echo -)" "$(cat "${b}_target" 2>/dev/null || echo -)"; done; [ "$found" = 0 ] && echo "   NO fan*_input anywhere — fans are not software-visible on this board"'
r 'c=0; for p in /sys/class/hwmon/hwmon*/pwm*; do [ -e "$p" ] && c=$((c+1)); done; echo "   pwm control nodes found: $c"'
r 'command -v sensors >/dev/null && sensors 2>&1 | head -40 || echo "lm-sensors not installed (apt install lm-sensors; sensors-detect needs sudo)"'

say "10. Storage — mounts, devices, IO source"
r 'lsblk -bno NAME,MODEL,SIZE,TYPE,MOUNTPOINTS 2>/dev/null | head -30'
r 'df -hT -x tmpfs -x devtmpfs -x overlay -x squashfs'
r 'findmnt -rn -o TARGET,SOURCE,FSTYPE 2>/dev/null | grep -vE "tmpfs|proc|sys|dev|cgroup|snap" | head -20'
r 'head -4 /proc/diskstats; echo "..."; wc -l < /proc/diskstats'
r 'ls /sys/class/nvme/ 2>&1; for n in /sys/class/nvme/nvme*; do [ -d "$n" ] || continue; printf "   %s model=%s state=%s\n" "$(basename "$n")" "$(cat "$n/model" 2>/dev/null)" "$(cat "$n/state" 2>/dev/null)"; done'
r 'command -v smartctl >/dev/null && echo "smartctl present (full report needs sudo)" || echo "smartctl absent (apt install smartmontools)"'

say "11. Network — interfaces, link ceiling for NETWORK panel, port 8080 availability"
r 'ip -br addr'
r 'for i in /sys/class/net/*; do printf "   %-12s speed=%s state=%s driver=%s\n" "$(basename "$i")" "$(cat "$i/speed" 2>/dev/null || echo "?")" "$(cat "$i/operstate" 2>/dev/null || echo ?)" "$(basename "$(readlink -f "$i/device/driver" 2>/dev/null)" 2>/dev/null || echo ?)"; done'
r 'ss -s 2>/dev/null | head -8'
r 'ss -ltnH 2>/dev/null | grep -q ":8080 " && echo "   PORT 8080 BUSY — choose another addr for marvind" || echo "   port 8080 free"'

say "12. Workloads Marvin will be watching (process list realism)"
r 'ps -eo comm,pcpu,pmem,rss --sort=-pcpu | head -12'
r 'command -v docker >/dev/null && { echo "docker present:"; timeout 5 docker ps --format "table {{.Names}}\t{{.Status}}" 2>&1 | head -12; } || echo "docker absent or not permitted for this user"'
r 'systemctl list-units --type=service --state=running --no-pager --no-legend 2>/dev/null | head -25'

say "13. Go toolchain + mandated quality tools"
r 'command -v go >/dev/null && go version || echo "GO ABSENT — install first"'
r 'command -v go >/dev/null && go env GOROOT GOPATH GOVERSION GOMODCACHE GOTOOLCHAIN'
r 'command -v golangci-lint >/dev/null && golangci-lint --version 2>&1 | head -2 || echo "golangci-lint ABSENT — make tools"'
r 'command -v govulncheck >/dev/null && govulncheck -version 2>&1 | head -1 || echo "govulncheck ABSENT — make tools"'
r 'command -v gitleaks >/dev/null && gitleaks version 2>&1 | head -1 || echo "gitleaks ABSENT — make tools"'
r 'git --version 2>&1; command -v make >/dev/null && make --version | head -1'

say "14. Marvin install targets (should be absent today)"
r 'id marvin 2>&1 | head -1; ls -ld /opt/marvin /var/lib/marvin 2>&1 | head -2'

cat <<'GAPS'

## Probe coverage gaps — require sudo, run separately with tools/discover-sudo.sh
- `smartctl -a` per disk: SMART health, reallocated sectors, power-on hours (STORAGE panel)
- `nvme smart-log /dev/nvme0`: NVMe composite temperature + percentage used (THERMALS panel)
- full DMI serials/board vendor; `dmidecode -t baseboard -t slot` for PCIe/HDMI topology
- `sensors-detect` to bind SuperIO fan channels (this is the ONLY way fan RPM may appear)
- `ethtool <iface>` for authoritative link speed if /sys reports -1
- `dmesg` for iGPU/HDMI hotplug errors and NVRM warnings
- BIOS settings are not readable from Linux at all: confirm "Initial Display Output /
  IGD Configuration" is not set to PEG-only before the panel is purchased.
GAPS
